### ISSUE TITLE
WebRTC using Dart

### ISSUE THREAD

**Issue by shenzhen-xi** [team-telnyx/webrtc#11]
Hello, 
can you test this package with Telnyx:
 
https://github.com/cloudwebrtc/dart-sip-ua

I have some trouble making it work

**Comment by pouledodue** [comment]
I need this too
We switched to Flutter and this package ^^ would do the job since Telnyx do not have a Flutter SDK

**Comment by pouledodue** [comment]
ref: https://github.com/cloudwebrtc/dart-sip-ua/issues/50

**Comment by DeividVeloso** [comment]
Hi shenzhen-xi and pouledodue we didn’t test this library yet https://github.com/cloudwebrtc/dart-sip-ua, but if you have some trouble integrating it you can send a message in our slack to get some help https://joinslack.telnyx.com/

**Comment by pouledodue** [comment]
@DeividVeloso done :)

**Comment by DeividVeloso** [comment]
If you want use React Native we have this library https://www.npmjs.com/package/@telnyx/react-native
