### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getItem')

### ISSUE THREAD

**Issue by prithi-netaesthetics** [team-telnyx/webrtc#265]
![simulator_screenshot_20728E27-46BE-4171-B79F-4DABEA37BCAD](https://user-images.githubusercontent.com/100333938/161676983-39373a99-f6a9-44a1-97c5-4e17637566bc.png)

**Comment by DeividVeloso** [comment]
Hi @prithi-netaesthetics, what is the project that you are using?

Which browser and version are you using?

**Comment by arghav** [comment]
Closing this as there's no response or enough info on the issue.
