### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by reyaz386** [team-telnyx/webrtc#288]
Hi Team :wave:- Would need your inputs on webRTC automation testing. We do use Telynx webrtc in our application.
When I am trying test webrtc in Selenium Grid - using chrome node.
Error in connection Establishment: net::ERR_CONNECTION_RESET
WebSocket Connection is closed before the connection is established.
FYI..Checking for audio and video permissions:
client.checkPermissions(); -> this return true
Any pointers will be really helpful.
<img width="637" alt="Screen Shot 2022-06-08 at 10 28 10 PM" src="https://user-images.githubusercontent.com/17481495/172775872-a5358d83-a818-4c27-b327-c405a026cb9d.png">

**Comment by DeividVeloso** [comment]
I am closing this issue, feel free to open a new one. 👍
