### ISSUE TITLE
Missing download

### ISSUE THREAD

**Issue by taf2** [team-telnyx/webrtc#308]
Missing a simple download of the compiled Javascript.

**Comment by RJSkorski** [comment]
Hi @taf2 

the SDK can be downloaded from the following external CDN's:
- https://unpkg.com/@telnyx/webrtc
- https://cdn.jsdelivr.net/npm/@telnyx/webrtc

We have updated our documentation and you can find more info on how to do that on that page: https://developers.telnyx.com/docs/v2/voice/webrtc/resources/js_client/
