### ISSUE TITLE
Browser crashing on new versions

### ISSUE THREAD

**Issue by alechirsch** [team-telnyx/webrtc#354]
I recently upgraded from 2.11.0 to 2.14.0 and noticed that after a call start, my fans take off and the browser tab freezes and eventually crashes. I narrowed it down to going from 2.11.0 to 2.12.0 and any version after. I am using the latest version of chrome.

**Comment by farhat-ha** [comment]
@alechirsch 👋🏾 
Can you give me more context about your problem? 
Are you using custom ICE servers ?

**Comment by alechirsch** [comment]
@farhat-ha Nothing custom, using it pretty standardly. Its embedded in an Ember.js application built using node 18. Followed the documentation here. Using latest version of chrome. It has been working on all versions 2.11.0 and below. As soon as I upgrade the telnyx webrtc version and change nothing else, the browser freezes after making a call and I need to kill it.

**Comment by farhat-ha** [comment]
@alechirsch We found the root issue to be the ice gathering process. It should be fixed in v2.22.1. Let me know if you still have problems after upgrading
