### ISSUE TITLE
Vanilla example missing a file

### ISSUE THREAD

**Issue by Optimaus50** [team-telnyx/webrtc#36]
There's a call out in the index.html code for "bundle.js" but it's not included.

`
    <script type="text/javascript" src="../../lib/bundle.js"></script>`

**Comment by DeividVeloso** [comment]
@Optimaus50 sorry, I will add this file. 

If you want to use it right now, please follow these steps:

1 - clone the project
2 - run `yarn` in the root folder
3 - cd `packages/js` && `yarn` && `yarn build`
4 - running the Vanilla example.

**Comment by DeividVeloso** [comment]
Fixed, now you can run the vanilla example, please run a git pull to get the update.
