### ISSUE TITLE
incoming is not working in telnyx web dialer

### ISSUE THREAD

**Issue by bajuddin15** [team-telnyx/webrtc#381]
I have built a web dialer using telnyx/webrtc, in this outgoing is working but incoming call is not coming in my dialer. please fix this

**Comment by EvanBarnesAZ** [comment]
Incoming calls are no longer working.

**Comment by EvanBarnesAZ** [comment]
This is affecting our entire platform, how can we fix this? It was working.

**Comment by brendan-chess** [comment]
experiencing this issue as well. we haven't changed our webrtc code and now it's not receiving any notifications for inbound calls. outbound works fine though. to debug i tried checking the registration status of my sip connection and can see that the user_agent field has "WebRTC Gateway" as the value, and last_registration field includes the timestamp of when i started webrtc last. seems like everything should be connected?

**Comment by farhat-ha** [comment]
Hey folks, Do you still have this problem when using [telnyx's dialer](https://webrtc.telnyx.com) ?
