### ISSUE TITLE
Flutter Web SDK?

### ISSUE THREAD

**Issue by pouledodue** [team-telnyx/webrtc#9]
Hi
Do you have a Flutter Web SDK for voice?

**Comment by DeividVeloso** [comment]
We don't support right now, but we will put it on our radar.

**Comment by pouledodue** [comment]
@DeividVeloso can you tell if the SDP is correct [here](https://github.com/cloudwebrtc/dart-sip-ua/issues/58#issuecomment-583883081) ?

**Comment by icodelifee** [comment]
Hi, are you folks working on voice sdk or official sdk for Flutter?

**Comment by fefecilly** [comment]
Any news about supporting Web platform?
